on:
  schedule:
    - cron:  '*/10 * * * *'
jobs:
  get-nvidia-supported-gpus-json:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - run: ls
      - run: ./get-nvidia-supported-gpus-json.sh
        shell: bash
      - uses: actions/upload-artifact@v2
        with:
            name: nvidia-upported-gpus-json
            path: ./supported-gpus.json
      - run: mkdir build
      - run: cp ./supported-gpus.json build
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
            branch: gh-pages
            folder: build
