name: get-nvidia-supported-gpus-json
on:
  schedule:
    - cron:  '0 */1 * * *'
  workflow_dispatch:

jobs:
  focal-get-nvidia-supported-gpus-json:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - run: ./get-nvidia-supported-gpus-json.sh
        shell: bash
      - run: mkdir build
      - run: cp ./*supported-gpus.json build
      - uses: actions/upload-artifact@v2
        with:
            name: artifact
            path: build/
  bionic-get-nvidia-supported-gpus-json:
    needs: focal-get-nvidia-supported-gpus-json
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - run: ./get-nvidia-supported-gpus-json.sh
        shell: bash
        # - run: mkdir build
      - name: download result from latest job
        uses: actions/download-artifact@v2
        with:
            name: artifact
            path: build
      - run: ls build
      - run: cp ./*supported-gpus.json build/
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
            branch: gh-pages
            folder: build
